name:  CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn run test
      - name: Run lint
        run: yarn run lint
      - name: Build project
        run: yarn run build
